# Generated by Django 4.2.20 on 2026-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
        ),
    ]
